export const portfolioData = {
  personal: {
    name: "Aboud Khalaf",
    role: "Flutter Developer | Mobile App Specialist",
    bio: "Bachelor of Applied Technologies graduate from Homs University (Ranked 1st in class, 90.9%). Expert in Dart, Bloc/Cubit, and Clean Architecture. Competitive programmer with 1,000+ algorithmic problems solved on Codeforces/LeetCode.",
    socials: [
      { name: "GitHub", url: "https://github.com", icon: "github" },
      { name: "LinkedIn", url: "https://linkedin.com", icon: "linkedin" },
      { name: "Medium", url: "https://medium.com", icon: "medium" },
      { name: "Codeforces", url: "https://codeforces.com", icon: "code" },
      { name: "LeetCode", url: "https://leetcode.com", icon: "terminal" },
    ],
  },
  skills: [
    "Dart",
    "Flutter",
    "Clean Architecture",
    "MVVM",
    "Supabase",
    "Firebase",
    "C++",
    "Git",
  ],
  professionalProjects: [
    {
      id: "tatbeeqi",
      slug: "tatbeeqi",
      title: "Tatbeeqi",
      role: "Lead Flutter Developer",
      shortDescription: "A comprehensive University Learning Platform designed to streamline the educational experience for students, featuring an integrated AI-powered assistant.",
      thumbnail: "https://picsum.photos/seed/tatbeeqi1/1600/900",
      techStack: ["Flutter", "Dart", "Firebase", "REST API", "AI Integration"],
    },
    {
      id: "pro-logistics",
      slug: "pro-logistics",
      title: "SwiftLogistics Pro",
      role: "Mobile Architect",
      shortDescription: "Enterprise-grade logistics management system with real-time fleet tracking, automated route optimization, and complex inventory analytics.",
      thumbnail: "https://picsum.photos/seed/trucks1/1600/900",
      techStack: ["Flutter", "Google Maps SDK", "Node.js", "Redis", "Supabase"],
    },
    {
      id: "fintech-vault",
      slug: "fintech-vault",
      title: "Secure Vault",
      role: "Security Engineer",
      shortDescription: "A security-first financial application for high-frequency trading assets, featuring multi-factor bio-authentication and hardware-level encryption.",
      thumbnail: "https://picsum.photos/seed/finance1/1600/900",
      techStack: ["Dart", "Clean Architecture", "Local Auth", "SQLite", "Encrypted Cache"],
    },
  ],
  personalProjects: [
    {
      id: "ketabk",
      slug: "ketabk",
      title: "Ketabk",
      role: "Flutter Developer",
      shortDescription: "An intuitive book discovery and tracking application powered by the Google Books API, allowing users to build and manage their personal digital libraries.",
      thumbnail: "/assets/projects/ketabk.png",
      techStack: ["Flutter", "Dart", "Cubit", "Google Books API", "Hive"],
    },
    {
      id: "etc-store",
      slug: "etc-store",
      title: "ETC Store",
      role: "Full Stack Developer",
      shortDescription: "A modern E-commerce application featuring real-time inventory synchronization, secure payment processing, and a fluid shopping cart experience.",
      thumbnail: "/assets/projects/etc_store.png",
      techStack: ["Flutter", "Dart", "Firebase", "Stripe", "Cloud Functions"],
    },
    {
      id: "wamada",
      slug: "wamada",
      title: "Wamada",
      role: "Flutter Developer",
      shortDescription: "A sleek, category-based News Application published on the Google Play Store, delivering curated content with a focus on user experience and performance.",
      thumbnail: "https://picsum.photos/seed/wamada1/1600/900",
      techStack: ["Flutter", "Dart", "Bloc", "SQLite", "REST API"],
    },

  ],
};
